name: just_debounce_it
description: A simple debounce library for preventing continuous execution of functions
version: 4.0.0
homepage: https://github.com/truthmast/just_debounce_it
author: Matt Hurst <matt@workpail.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: ^1.16.5