name: just_debounce_it
description: A simple debounce library
version: 2.1.0
homepage: https://github.com/localhurst/just_debounce_it
author: Matt Hurst <matt@qrl.app>

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  test: ^1.3.0