name: just_debounce_it
description: A simple debounce library
version: 1.0.3
homepage: https://github.com/localhurst/just_debounce_it
author: Matthew Hurst <localhurst@gmail.com>

environment:
  sdk: '>=1.24.0 <2.0.0'

dev_dependencies:
  test: ^0.12.0